#!/usr/sbin/nft -f

flush ruleset

# The cluster_network variable is passed from Ansible
define CLUSTER_NET = {{ cluster_network }}
# monitoring server's ip is also being passed from ansible down to host 
define CLUSTER_MONITOR = {{ hostvars[groups[target_cluster ~ '_monitor'][0]]['ansible_host'] }}

table inet filter {
    set ssh_ban_list_ipv4 { type ipv4_addr; flags dynamic, timeout; timeout 30m; }
    set ssh_ban_list_ipv6 { type ipv6_addr; flags dynamic, timeout; timeout 30m; }

    chain inbound_ipv4 {
        ct state invalid drop
        iifname != "lo" ip saddr 127.0.0.0/8 drop
        ct state established,related accept
        
        # ICMP (Ping)
        ip protocol icmp accept

        # Trust the internal Physical Network (High Importance for K8s)
        ip saddr $CLUSTER_NET accept

        # Calico Data Plane: IP-in-IP (Protocol 4) and BGP (Port 179)
        ip protocol 4 accept
        tcp dport 179 accept

        ip protocol tcp saddr $CLUSTER_MONITOR dport 10050 accept 

        # SSH Brute Force Protection (Port 22)
        ip saddr @ssh_ban_list_ipv4 drop
        tcp dport 22 ct state new limit rate over 3/minute add @ssh_ban_list_ipv4 { ip saddr } drop
        tcp dport 22 ct state new accept
    }

    chain inbound_ipv6 {
        ct state invalid drop
        iifname != "lo" ip6 saddr ::1 drop
        ct state established,related accept
        
        # ICMPv6
        icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem, echo-request, echo-reply, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert } accept

        # SSH Protection
        ip6 saddr @ssh_ban_list_ipv6 drop
        tcp dport 22 ct state new limit rate over 3/minute add @ssh_ban_list_ipv6 { ip6 saddr } drop
        tcp dport 22 ct state new accept
    }

    chain input {
        type filter hook input priority 0; policy drop;
        iifname "lo" accept
        
        meta protocol vmap { ip : jump inbound_ipv4, ip6 : jump inbound_ipv6 }

        # K8s Management (API Server, Kubelet)
        tcp dport { 6443, 8443, 10250 } accept

        # Core Services
        udp dport 53 accept
        tcp dport { 80, 443 } accept
        
        # Log dropped packets (Rate limited to prevent disk fill)
        limit rate 5/second log prefix "NFT_INPUT_DROP: "
    }

    chain output {
        type filter hook output priority 0; policy accept;
        # Policy accept ensures Pods can reach external APIs/Registries easily.
    }
}