# Generated by Django 5.2.13 on 2026-05-05 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('cluster_cidr', models.CharField(default='192.168.0.0/16', max_length=64)),
                ('vip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('kube_version', models.CharField(default='1.35', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ip', models.GenericIPAddressField()),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('worker', 'Worker')], db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='clusters.cluster')),
            ],
            options={
                'ordering': ['role', 'name'],
                'unique_together': {('cluster', 'name')},
            },
        ),
    ]
