# Generated by Django 6.0.4 on 2026-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('deploying', 'Deploying'), ('healthy', 'Healthy'), ('error', 'Error')], db_index=True, default='deploying', max_length=16),
        ),
    ]
