# Generated by Django 6.0.4 on 2026-05-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_node_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('deploying', 'Deploying'), ('healthy', 'Healthy'), ('deleting', 'Deleting'), ('error', 'Error')], db_index=True, default='deploying', max_length=16),
        ),
    ]
