---
- name: Remove node from cluster
  hosts: "{{ target_cluster }}_managers[0]"  # Target the first manager in inventory
  become: true

  tasks:
    - name: Drain the node # To ensure minimal downtime for application in cluster
      ansible.builtin.command: "kubectl drain {{ target_node }} --ignore-daemonsets --delete-emptydir-data --force"
      environment: 
        KUBECONFIG: /etc/kubernetes/admin.conf
      ignore_errors: true

    - name: Delete the node from cluster
      ansible.builtin.command: "kubectl delete node {{ target_node }}"
      environment: 
        KUBECONFIG: /etc/kubernetes/admin.conf
      ignore_errors: true

- name: Wipe the target node
  hosts: "{{ target_node }}"
  become: true

  tasks:
  - name: Use ../tasks/cleanup_node.yml to wipe the node
    ansible.builtin.import_tasks: ../tasks/cleanup_node.yml