---
- name: Retrieve join command from manager
  hosts: "{{ target_cluster }}_managers"
  become: true
  tasks:
    - name: Get token
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Save to memory
      ansible.builtin.set_fact:
        worker_join_command: "{{ join_command_raw.stdout }}"

- name: Deploy Worker Node
  hosts: "{{ target_cluster }}_workers"
  become: true

  vars:
      KUBE_VERSION: "{{ kube_version | default('1.35') }} "
  
  tasks:
    - name: Run General Setup Phase
      ansible.builtin.import_tasks: ../tasks/general_setup.yml

    - name: Run Worker Join Phase
      ansible.builtin.import_tasks: ../tasks/join_worker.yml