---
- name: Heal interrupted package manager state
  ansible.builtin.command: dpkg --configure -a
  become: true
  ignore_errors: true

- name: Reset k8s cluster state
  ansible.builtin.command: "kubeadm reset -f"
  register: kubeadm_reset
  ignore_errors: true

- name: Stop and disable containerd
  ansible.builtin.systemd:
    name: containerd
    state: stopped
    enabled: false
  ignore_errors: true

- name: Remove Kubernetes and container packages
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni
      - containerd
    state: absent
    autoremove: yes
    purge: yes
    lock_timeout: 120
    allow_change_held_packages: true

- name: Remove Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version | default('1.35') }}/deb/ /"
    state: absent

- name: Remove configuration directories and files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes
    - /var/lib/etcd
    - /var/lib/kubelet
    - /etc/cni
    - /opt/cni
    - /etc/containerd
    - /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - /root/.kube
    - /home/ansible/.kube

# If node has to be th  part of NEW cluster this step is crucial
- name: Clean up lingering CNI network interfaces
  ansible.builtin.shell: |
    ip link delete cni0 || true
    ip link delete flannel.1 || true
    ip link delete kube-ipvs0 || true
    ip link delete nodelocaldns || true
    ip link delete vxlan.calico || true
    ip link delete tunl0 || true
  ignore_errors: true
  changed_when: false

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes