#!/bin/bash
set -euo pipefail

# ─── Config ──────────────────────────────────────────────────────────────────
KUBE_VERSION="${1:-1.35}"
POD_CIDR="${2:-192.168.0.0/16}" # Updated to Calico's default CIDR
CNI_MANIFEST="https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml"
JOIN_TOKEN_FILE="/etc/kubernetes/join-command.sh"
LOG_FILE="/var/log/k8s-manager-setup.log"
INSTALL_KUBECTL="true"   # managers need kubectl; workers don't

# ─── Common node setup (swap, modules, sysctl, containerd, k8s packages) ─────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=setup_node.sh
source "${SCRIPT_DIR}/setup_node.sh"

# ─── Banner ───────────────────────────────────────────────────────────────────
log "════════════════════════════════════════════════════════"
log "  Manager setup  |  k8s v${KUBE_VERSION}  |  CIDR ${POD_CIDR}"
log "════════════════════════════════════════════════════════"

# ─── 6. Initialise control plane ─────────────────────────────────────────────
step "kubeadm-init"
if [[ -f /etc/kubernetes/admin.conf ]]; then
  skip "Control plane already initialised (/etc/kubernetes/admin.conf exists)."
else
  kubeadm init \
    --pod-network-cidr="${POD_CIDR}" \
    --kubernetes-version="v${KUBE_VERSION}" \
    2>&1 | tee -a "$LOG_FILE" \
    || die "kubeadm init failed — run 'kubeadm reset -f' to clean up before retrying."
  ok "Control plane initialised."
fi

# ─── 7. Kubeconfig ───────────────────────────────────────────────────────────
step "kubeconfig"
REAL_USER="${SUDO_USER:-$USER}"
REAL_HOME=$(eval echo "~${REAL_USER}")

mkdir -p "${REAL_HOME}/.kube"
if [[ ! -f "${REAL_HOME}/.kube/config" ]]; then
  cp /etc/kubernetes/admin.conf "${REAL_HOME}/.kube/config"
  chown "$(id -u "${REAL_USER}"):$(id -g "${REAL_USER}")" "${REAL_HOME}/.kube/config"
  ok "kubeconfig written to ${REAL_HOME}/.kube/config."
else
  skip "kubeconfig already exists at ${REAL_HOME}/.kube/config."
fi
export KUBECONFIG=/etc/kubernetes/admin.conf

# ─── 8. CNI — Calico ─────────────────────────────────────────────────────────
step "cni-calico"
# Calico deploys the calico-node DaemonSet in the kube-system namespace
if kubectl get daemonset calico-node -n kube-system \
    --kubeconfig=/etc/kubernetes/admin.conf &>/dev/null; then
  skip "Calico CNI already deployed."
else
  kubectl apply -f "${CNI_MANIFEST}" --kubeconfig=/etc/kubernetes/admin.conf \
    >> "$LOG_FILE" 2>&1
  ok "Calico CNI applied."
fi

# ─── 9. Join token ───────────────────────────────────────────────────────────
step "join-token"
JOIN_CMD=$(kubeadm token create --print-join-command 2>> "$LOG_FILE") \
  || die "Failed to generate join token."

{
  echo "#!/bin/bash"
  echo "# Generated by create_manager.sh on $(date)"
  echo "set -euo pipefail"
  echo "${JOIN_CMD}"
} > "${JOIN_TOKEN_FILE}"
chmod 600 "${JOIN_TOKEN_FILE}"
ok "Join command saved to ${JOIN_TOKEN_FILE}."

# ─── Done ────────────────────────────────────────────────────────────────────
log ""
log "════════════════════════════════════════════════════════"
log "  Manager setup complete!"
log "  Copy ${JOIN_TOKEN_FILE} to each worker, then run:"
log "    sudo bash /etc/kubernetes/join-command.sh"
log ""
log "  Verify:"
log "    kubectl get nodes"
log "    kubectl get pods -n kube-system"
log "════════════════════════════════════════════════════════"