all:
    children:
        global_managers:
            children:
                anothertest_managers: {}
        global_workers:
            children:
                anothertest_workers: {}
        global_monitor:
            children: {}
        clusters:
            children:
                anothertest:
                    children:
                        anothertest_managers:
                            hosts: {}
                        anothertest_workers:
                            hosts: {}
                    vars:
                        cluster_vip: 172.16.86.200
                        control_plane_endpoint: 172.16.86.200:8443
