all:
    children:
        global_managers:
            children:
                presentation_cluster_managers: {}
        global_workers:
            children:
                presentation_cluster_workers: {}
        clusters:
            children:
                presentation_cluster:
                    children:
                        presentation_cluster_workers:
                            hosts:
                                presentation-worker:
                                    ansible_host: 172.16.86.130
                        presentation_cluster_managers:
                            hosts:
                                presentation-manager:
                                    ansible_host: 172.16.86.131
