all:
    children:
        global_managers:
            children:
                my-cluster_managers: {}
        global_workers:
            children:
                my-cluster_workers: {}
        clusters:
            children:
                my-cluster:
                    children:
                        my-cluster_managers:
                            hosts:
                                new-manager:
                                    ansible_host: 172.16.86.130
                        my-cluster_workers:
                            hosts:
                                new-worker:
                                    ansible_host: 172.16.86.131
