---
- name: Deploy Manager
  hosts: manager_nodes
  remote_user: ansible
  become: yes

  tasks:
    - name: Run general script
      ansible.builtin.script: scripts/general_setup.sh
      args:
        executable: /bin/bash
        creates: /usr/bin/kubelet

    - name: Run create manager script
      ansible.builtin.script: scripts/create_manager.sh
      args:
        executable: /bin/bash